dist: focal
os: linux
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - nosetests -v -l DEBUG --logging-level=DEBUG --with-coverage --cover-package=amqpstorm_pool --with-timer --timer-top-n 10
  - flake8 .
